In [4]:
import pandas as pd

## 1) read_csv() => CSV dosyasını okur.

In [15]:
df1 = pd.read_csv("prog_book.csv")
df1

,Rating,Reviews,Book_title,Description,Number_Of_Pages,Type,Price
0,4.17,"3,829",The Elements of Style,This style manual offers practical advice on i...,105,Hardcover,9.323529
1,4.01,"1,406","The Information: A History, a Theory, a Flood","James Gleick, the author of the best sellers C...",527,Hardcover,11.000000
2,3.33,0,Responsive Web Design Overview For Beginners,In Responsive Web Design Overview For Beginner...,50,Kindle Edition,11.267647
3,3.97,"1,658",Ghost in the Wires: My Adventures as the World...,If they were a hall of fame or shame for compu...,393,Hardcover,12.873529
4,4.06,"1,325",How Google Works,Both Eric Schmidt and Jonathan Rosenberg came ...,305,Kindle Edition,13.164706
...,...,...,...,...,...,...,...
266,3.76,0,3D Game Engine Architecture: Engineering Real-...,Dave Eberly's 3D Game Engine Design was the fi...,752,Hardcover,203.108823
267,3.94,22,An Introduction to Database Systems,"Continuing in the eighth edition, An Introduct...",1040,Paperback,212.097059
268,4.49,36,"The Art of Computer Programming, Volumes 1-3 B...",Knuth's classic work has been widely acclaimed...,896,Boxed Set - Hardcover,220.385294
269,4.77,4,"The Art of Computer Programming, Volumes 1-4a ...","""The bible of all fundamental algorithms and t...",3168,Hardcover,220.385294
270,3.84,5,A Discipline for Software Engineering,Designed to help individual programmers develo...,789,Hardcover,235.650000

## 2) duplicated() =>  Yinelenen satırları kontrol eder.

In [16]:
df1.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
266    False
267    False
268    False
269    False
270    False
Length: 271, dtype: bool

## 3) info)() => Veri çerçevesi hakkında bilgi verir.

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271 entries, 0 to 270
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Rating           271 non-null    float64
 1   Reviews          271 non-null    object
 2   Book_title       271 non-null    object
 3   Description      271 non-null    object
 4   Number_Of_Pages  271 non-null    int64
 5   Type             271 non-null    object
 6   Price            271 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 14.9+ KB

## 4) describe() => Temel istatistiksel özet sağlar.

In [18]:
df1.describe()

           Rating  Number_Of_Pages       Price
count  271.000000       271.000000  271.000000
mean     4.067417       475.077491   54.541860
std      0.290749       306.147492   35.711485
min      3.000000        50.000000    9.323529
25%      3.915000       289.000000   30.751471
50%      4.100000       384.000000   46.317647
75%      4.250000       572.500000   67.854412
max      5.000000      3168.000000  235.650000

## 5) sample() => Rastgele satır örnekleri seçer.

In [27]:
df1.sample()

,Rating,Reviews,Book_title,Description,Number_Of_Pages,Type,Price
141,4.08,168,Test Driven Development: By Example,"Quite simply, test-driven development is meant...",216,Paperback,48.629412

## 6) rename() => Sütun veya indeks adlarını değiştirir.

In [28]:
df1.rename(columns={'Number_Of_Pages' : 'Sayfa_Sayısı'})

,Rating,Reviews,Book_title,Description,Sayfa_Sayısı,Type,Price
0,4.17,"3,829",The Elements of Style,This style manual offers practical advice on i...,105,Hardcover,9.323529
1,4.01,"1,406","The Information: A History, a Theory, a Flood","James Gleick, the author of the best sellers C...",527,Hardcover,11.000000
2,3.33,0,Responsive Web Design Overview For Beginners,In Responsive Web Design Overview For Beginner...,50,Kindle Edition,11.267647
3,3.97,"1,658",Ghost in the Wires: My Adventures as the World...,If they were a hall of fame or shame for compu...,393,Hardcover,12.873529
4,4.06,"1,325",How Google Works,Both Eric Schmidt and Jonathan Rosenberg came ...,305,Kindle Edition,13.164706
...,...,...,...,...,...,...,...
266,3.76,0,3D Game Engine Architecture: Engineering Real-...,Dave Eberly's 3D Game Engine Design was the fi...,752,Hardcover,203.108823
267,3.94,22,An Introduction to Database Systems,"Continuing in the eighth edition, An Introduct...",1040,Paperback,212.097059
268,4.49,36,"The Art of Computer Programming, Volumes 1-3 B...",Knuth's classic work has been widely acclaimed...,896,Boxed Set - Hardcover,220.385294
269,4.77,4,"The Art of Computer Programming, Volumes 1-4a ...","""The bible of all fundamental algorithms and t...",3168,Hardcover,220.385294
270,3.84,5,A Discipline for Software Engineering,Designed to help individual programmers develo...,789,Hardcover,235.650000

## 7) pivot_table(): Özet tablo oluşturur.

In [44]:
pivot = pd.pivot_table(df1, values='Reviews', index='Type', columns='Book_title', aggfunc='sum', margins=True)
#print(pivot)

## 8) rank() => Verileri sıralar ve sıralama pozisyonu döner.

In [35]:
df1.rank()

     Rating  Reviews  Book_title  Description  Number_Of_Pages   Type  Price
0     170.5    152.0       232.0        232.0              2.0   49.0    1.0
1     101.5     43.0       236.0        128.0            188.0   49.0    2.0
2       7.0     11.5       196.0        114.0              1.0  101.5    3.0
3      87.5     44.0       120.0        106.0            147.0   49.0    4.0
4     122.5     42.0       128.0         45.0             77.0  101.5    5.0
..      ...      ...         ...          ...              ...    ...    ...
266    31.5     11.5         1.0         64.0            230.0   49.0  267.0
267    76.0    123.5        22.0         60.0            258.0  184.5  268.0
268   258.5    168.0       218.0        132.0            245.0    1.0  269.5
269   270.0    182.0       219.0          8.0            271.0   49.0  269.5
270    49.0    207.0         5.0         65.0            233.0   49.0  271.0

[271 rows x 7 columns]

## 9) sort_values() => Verileri belirli bir sütuna göre sıralar

In [42]:
df1.sort_values(by = 'Rating', ascending=False )

,Rating,Reviews,Book_title,Description,Number_Of_Pages,Type,Price
54,5.00,0,Your First App: Node.js,A tutorial for real-world application developm...,317,ebook,25.855882
269,4.77,4,"The Art of Computer Programming, Volumes 1-4a ...","""The bible of all fundamental algorithms and t...",3168,Hardcover,220.385294
131,4.72,362,Designing Data-Intensive Applications: The Big...,Want to know how the best software engineers a...,616,Paperback,45.561765
114,4.67,1,Build Web Applications with Java: Learn every ...,This book is primarily intended for beginners ...,372,Paperback,42.276471
194,4.67,78,"Fluent Python: Clear, Concise, and Effective P...",Python's simplicity lets you become productive...,792,Paperback,64.091176
...,...,...,...,...,...,...,...
86,3.22,2,Beginning Java 2,What is this book about? The Java language has...,1200,Paperback,36.617647
24,3.20,0,Game Programming Golden Rules,'Game Programming Golden Rules' provides indis...,318,Paperback,19.152941
177,3.00,0,Advanced Game Programming: A Gamedev.Net Colle...,"Welcome to ""Advanced Game Programming: A GameD...",464,Paperback,59.082353
182,3.00,0,Cross-Platform Game Programming (Game Developm...,With many of today's games being released simu...,460,Paperback,60.391176
187,3.00,0,"Lambda-Calculus, Combinators and Functional Pr...","Originally published in 1988, this book presen...",192,Paperback,61.167647

## 10) value_counts() => Bir sütundaki her bir benzersiz değerin kaç kere tekrar ettiğini sayar.

In [43]:
df1['Type'].value_counts()

Type
Paperback                156
Hardcover                 95
Kindle Edition            10
ebook                      7
Unknown Binding            2
Boxed Set - Hardcover      1
Name: count, dtype: int64